$axure.loadCurrentPage({
  "url":"登陆.html",
  "generationDate":new Date(1460465362499.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"096c91ff869443c792ed648cac8b2178",
    "type":"Axure:Page",
    "name":"登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4121e1d0f2c947718c2c57ccef246d84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'黑体-繁 细体', '黑体-繁'",
            "fontSize":"48px",
            "fontWeight":"300",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":564,
              "y":81},
            "size":{
              "width":126,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49293d50fdaa480ebacd340b0c13809b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体-繁 细体', '黑体-繁'",
                "fontSize":"48px",
                "fontWeight":"300",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":564,
                  "y":81},
                "size":{
                  "width":126,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ca46622582b4438980adcf9aa0eb246",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":335},
            "size":{
              "width":240,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":1}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98694ceb0cfa43c8adcafdcddb08251d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":335},
                "size":{
                  "width":240,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":1}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/border_u2.png"}},
{
          "id":"8d8f74ef25fd4c35bba6421163ca3739",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":391},
            "size":{
              "width":240,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":1}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b67a19244a5444eb802b1e28c93d51af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":391},
                "size":{
                  "width":240,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":1}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/border_u2.png"}},
{
          "id":"9b967692cd2e48b88a09cffc4e3e1a59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":677,
              "y":510},
            "size":{
              "width":93,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ad7b7a87b194765ad0b8df1f2d40edc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":677,
                  "y":510},
                "size":{
                  "width":93,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 注册 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u6.png"}},
{
          "id":"45c75589abd649c8b327819dda27b7a2",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":535,
              "y":335},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"使用手机号登陆"},
{
          "id":"82c517db2cf34f35a90314a807cdfa8b",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":535,
              "y":391},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"密码"},
{
          "id":"edc75d2ce74641c28be51ed3a83b0aad",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'黑体-繁 细体', '黑体-繁'",
            "fontSize":"28px",
            "fontWeight":"300",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":430,
              "y":190},
            "size":{
              "width":430,
              "height":67}},
          "adaptiveStyles":{
},
          "placeholderText":"在路上认识世界，在途中认清自己"},
{
          "id":"134d8d7b4cc34c98943cb9d512519215",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":540,
              "y":510},
            "size":{
              "width":93,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24b5701ae8ea4e698724ab86b2ccad2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":540,
                  "y":510},
                "size":{
                  "width":93,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  }]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4121e1d0f2c947718c2c57ccef246d84":{
      "scriptId":"u0"},
    "49293d50fdaa480ebacd340b0c13809b":{
      "scriptId":"u1"},
    "7ca46622582b4438980adcf9aa0eb246":{
      "scriptId":"u2"},
    "98694ceb0cfa43c8adcafdcddb08251d":{
      "scriptId":"u3"},
    "8d8f74ef25fd4c35bba6421163ca3739":{
      "scriptId":"u4"},
    "b67a19244a5444eb802b1e28c93d51af":{
      "scriptId":"u5"},
    "9b967692cd2e48b88a09cffc4e3e1a59":{
      "scriptId":"u6"},
    "0ad7b7a87b194765ad0b8df1f2d40edc":{
      "scriptId":"u7"},
    "45c75589abd649c8b327819dda27b7a2":{
      "scriptId":"u8"},
    "82c517db2cf34f35a90314a807cdfa8b":{
      "scriptId":"u9"},
    "edc75d2ce74641c28be51ed3a83b0aad":{
      "scriptId":"u10"},
    "134d8d7b4cc34c98943cb9d512519215":{
      "scriptId":"u11"},
    "24b5701ae8ea4e698724ab86b2ccad2d":{
      "scriptId":"u12"}}});