$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1460465362441.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"29603f95cb6e4d3983c746aa8d56a376",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ee1dd92177e44adb922a05b7464003f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'黑体-繁 细体', '黑体-繁'",
            "fontSize":"48px",
            "fontWeight":"300",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":564,
              "y":81},
            "size":{
              "width":126,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73ad02a608624cf7bf354c19ae2a76b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体-繁 细体', '黑体-繁'",
                "fontSize":"48px",
                "fontWeight":"300",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":564,
                  "y":81},
                "size":{
                  "width":126,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f9f78a7c8a54d0c816208bbc36d6c37",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":281},
            "size":{
              "width":240,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":1}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91c9fa8611c842d19b2389e8de3d23ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":281},
                "size":{
                  "width":240,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":1}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/border_u2.png"}},
{
          "id":"1091d5f65d5041e1b47d452f9605792d",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":335},
            "size":{
              "width":240,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":1}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c91f1f1e3c25439ca7e5e3001d3fc09c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":335},
                "size":{
                  "width":240,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":1}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/border_u2.png"}},
{
          "id":"fc0132fb91934a69b35c11c16bfd5373",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":391},
            "size":{
              "width":240,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":1}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd82c2dc33d4e38a7afee93d71c3fb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":391},
                "size":{
                  "width":240,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":1}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/border_u2.png"}},
{
          "id":"35c1e3fa969f485592ee6ad3296bcca3",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":445},
            "size":{
              "width":240,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":1}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"327e6cd3e777438daa6083644db6a151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":445},
                "size":{
                  "width":240,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":1}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/border_u2.png"}},
{
          "id":"f7d6d75a18214d7eb0ad001a78ab015c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":537,
              "y":510},
            "size":{
              "width":233,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c05ef38ade74ae495305bc96cf3ce39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":537,
                  "y":510},
                "size":{
                  "width":233,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u10.png"}},
{
          "id":"b0a5fc70da2b4b10bd00b47b3a53a9e3",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":540,
              "y":281},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"姓名"},
{
          "id":"d7e379a2d0974459a9e55b1478574c8f",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":535,
              "y":335},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"手机号（仅支持中国大陆）"},
{
          "id":"70df6782f3414cf58fac0814dff9c6be",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":535,
              "y":391},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"密码（不少于6位，包含数字和字母）"},
{
          "id":"28b21455d5c24458b91369b2461f1754",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":535,
              "y":445},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"重复密码"},
{
          "id":"69b998c3270e4c4dafb647a95f90c065",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'黑体-繁 细体', '黑体-繁'",
            "fontSize":"28px",
            "fontWeight":"300",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":430,
              "y":190},
            "size":{
              "width":430,
              "height":67}},
          "adaptiveStyles":{
},
          "placeholderText":"在路上认识世界，在途中认清自己"},
{
          "id":"abf6d6d620ae4709b21706f9ed4b72ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":577,
              "y":554},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f761b9c436954f79b59144ec9e459d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":577,
                  "y":554},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登陆 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登陆.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册/u17.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ee1dd92177e44adb922a05b7464003f1":{
      "scriptId":"u0"},
    "73ad02a608624cf7bf354c19ae2a76b7":{
      "scriptId":"u1"},
    "1f9f78a7c8a54d0c816208bbc36d6c37":{
      "scriptId":"u2"},
    "91c9fa8611c842d19b2389e8de3d23ec":{
      "scriptId":"u3"},
    "1091d5f65d5041e1b47d452f9605792d":{
      "scriptId":"u4"},
    "c91f1f1e3c25439ca7e5e3001d3fc09c":{
      "scriptId":"u5"},
    "fc0132fb91934a69b35c11c16bfd5373":{
      "scriptId":"u6"},
    "acd82c2dc33d4e38a7afee93d71c3fb5":{
      "scriptId":"u7"},
    "35c1e3fa969f485592ee6ad3296bcca3":{
      "scriptId":"u8"},
    "327e6cd3e777438daa6083644db6a151":{
      "scriptId":"u9"},
    "f7d6d75a18214d7eb0ad001a78ab015c":{
      "scriptId":"u10"},
    "6c05ef38ade74ae495305bc96cf3ce39":{
      "scriptId":"u11"},
    "b0a5fc70da2b4b10bd00b47b3a53a9e3":{
      "scriptId":"u12"},
    "d7e379a2d0974459a9e55b1478574c8f":{
      "scriptId":"u13"},
    "70df6782f3414cf58fac0814dff9c6be":{
      "scriptId":"u14"},
    "28b21455d5c24458b91369b2461f1754":{
      "scriptId":"u15"},
    "69b998c3270e4c4dafb647a95f90c065":{
      "scriptId":"u16"},
    "abf6d6d620ae4709b21706f9ed4b72ac":{
      "scriptId":"u17"},
    "f761b9c436954f79b59144ec9e459d03":{
      "scriptId":"u18"}}});